pipeline {
    agent any

    stages {

        stage ('Apply Service') {
            steps {
                sh "kubectl apply -f k8/dev/service.yml"
            }

        }
        stage ('Apply Deployment') {
            steps {
                sh 'cat k8/dev/deployment.yml | sed "s/{{TAG}}/$TAG/g" | kubectl apply -f -'


            }

        }

    }
}
