pipeline {
    agent { label 'bastion'}
    parameters {
        string defaultValue: '', description: 'Nombre del usuario a crear', name: 'USUARIO', trim: true
        string defaultValue: '', description: 'contraseña nueva del usuario a crear', name: 'PASSWORD', trim: true
    }
    stages {
        stage ('Creando Usuario') {
            steps {
                        script {
                           sh  "sudo useradd -d /home/$USUARIO  -m -p \$(echo '$PASSWORD' | openssl passwd -1 -stdin) $USUARIO"
                    }
                
            }
        }
    }
}
